Repository AY2122S2-CS2103T-T17-2/tp, pull requests merged in 2022-04, with the labels that each got.

#181 fix: update assertion
  docs/umlDiagrams/ComponentManagers.puml
  docs/umlDiagrams/LogicClassDiagram.puml
  docs/umlDiagrams/ParserClasses.puml
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.High

#221 docs: add exit command description, more description for find command and remove invalid line breaking
  docs/UserGuide.md
Labels: priority.High

#170 test: small update to Storage test to get 100% code coverage
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/model/recipe/Ingredient.java
  src/main/java/seedu/address/storage/JsonAdaptedIngredient.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Test

#223 fix: UI related bugs
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecipeListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Bug

#246 docs: update PPP
  docs/team/blaketingyu.md
Labels: priority.High

#245 docs: updated UML diagrams
  docs/umlDiagrams/ArchitectureSequenceDiagram.puml
  docs/umlDiagrams/ClassDiagrams.puml
  docs/umlDiagrams/ComponentManagers.puml
  docs/umlDiagrams/DeleteSequenceDiagram.puml
  docs/umlDiagrams/LogicClassDiagram.puml
  docs/umlDiagrams/ModelClassDiagram.puml
  docs/umlDiagrams/ParserClasses.puml
  docs/umlDiagrams/StorageClassDiagram.puml
  docs/umlDiagrams/Style.puml
  docs/umlDiagrams/UiClassDiagram.puml
  docs/umlDiagrams/img/ArchitectureDiagram.png
  docs/umlDiagrams/img/ArchitectureSequenceDiagram.png
  docs/umlDiagrams/img/ClassDiagrams.png
  docs/umlDiagrams/img/ComponentManagers.png
  docs/umlDiagrams/img/DeleteSequenceDiagram.png
  docs/umlDiagrams/img/LogicClassDiagram.png
  docs/umlDiagrams/img/ModelClassDiagram.png
  docs/umlDiagrams/img/ParserClasses.png
  docs/umlDiagrams/img/StorageClassDiagram.png
  docs/umlDiagrams/img/UiClassDiagram.png
Labels: priority.Medium
