Repository AY2122S2-CS2103T-T17-2/tp, pull requests merged in 2022-02, with the labels that each got.

#18 docs: update PPP and AboutUs -- Yusuf
  docs/team/yusufaine.md
Labels: type.Chore, priority.High

#26 docs: Update Gigi's info
  docs/.Rhistory
  docs/AboutUs.md
  docs/images/gigituang.png
  docs/team/gigituang.md
Labels: priority.High

#27 docs: fix file name for photo and ppp
  docs/images/blaketingyu.png
  docs/team/blaketingyu.md
Labels: type.Chore, priority.High

#29 docs: update Ui.png to mockup
  docs/images/Ui.png
Labels: type.Chore, priority.High

#12 feat!: modify files in Model for our use case
  src/main/java/seedu/address/model/ReadOnlyRecipeBook.java
  src/main/java/seedu/address/model/RecipeBook.java
  src/main/java/seedu/address/model/RecipeBookModel.java
  src/main/java/seedu/address/model/RecipeBookModelManager.java
  src/main/java/seedu/address/model/RecipeBookUserPrefs.java
  src/main/java/seedu/address/model/recipe/Ingredient.java
  src/main/java/seedu/address/model/recipe/Name.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/recipe/UniqueRecipeList.java
  src/main/java/seedu/address/model/recipe/exceptions/DuplicateRecipeFoundException.java
  src/main/java/seedu/address/model/recipe/exceptions/RecipeNotFoundException.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/RecipeBookSampleDataUtil.java
Labels: priority.High

#38 refactor: rename directions variable to steps
  src/main/java/seedu/address/model/recipe/Recipe.java
Labels: priority.Low

#44 Feat: Add feature storage for McKitchen
  .gitignore
  src/main/java/seedu/address/model/recipe/CompletionTime.java
  src/main/java/seedu/address/model/recipe/Portion.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/recipe/Step.java
  src/main/java/seedu/address/newstorage/JsonAdaptedIngredient.java
  src/main/java/seedu/address/newstorage/JsonAdaptedRecipe.java
  src/main/java/seedu/address/newstorage/JsonAdaptedStep.java
  src/main/java/seedu/address/newstorage/JsonAdaptedTag.java
  src/main/java/seedu/address/newstorage/JsonRecipeBookStorage.java
  src/main/java/seedu/address/newstorage/JsonSerializableRecipeBook.java
  src/main/java/seedu/address/newstorage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/newstorage/RecipeBookStorage.java
  src/main/java/seedu/address/newstorage/Storage.java
  src/main/java/seedu/address/newstorage/StorageManager.java
  src/main/java/seedu/address/newstorage/UserPrefsStorage.java
Labels: type.Story, priority.High
