Repository AY2122S2-CS2103T-T17-2/tp, pull requests merged in 2022-03, with the labels that each got.

#48 docs: updated DG
  docs/umlDiagrams/ClassDiagrams.puml
  docs/umlDiagrams/DeleteSequenceDiagram.puml
  docs/umlDiagrams/Style.puml
Labels: priority.High

#50 docs: Update DG with Model's Class Diagram
  docs/.Rhistory
  docs/DeveloperGuide.md
  docs/umlDiagrams/ClassDiagrams.puml
  docs/umlDiagrams/ModelClassDiagram.puml
  docs/umlDiagrams/img/ModelClassDiagram.png
Labels: priority.High

#47 feat!: create new Parser class based on AB3
  docs/DeveloperGuide.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/logic/parser/RecipeBookParserUtil.java
  src/main/java/seedu/address/logic/parser/RecipeBookSyntax.java
  src/main/java/seedu/address/model/recipe/Ingredient.java
  src/main/java/seedu/address/model/recipe/Name.java
  src/main/java/seedu/address/model/recipe/Portion.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/recipe/ServingSize.java
  src/main/java/seedu/address/model/recipe/UniqueRecipeList.java
  src/main/java/seedu/address/newstorage/JsonAdaptedIngredient.java
  src/main/java/seedu/address/newstorage/JsonAdaptedRecipe.java
Labels: priority.High

#58 fix(RecipeBookParserUtil): add missing parseTag/parseTags functions
  src/main/java/seedu/address/logic/parser/RecipeBookParserUtil.java
  src/main/java/seedu/address/logic/parser/RecipeBookSyntax.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug, priority.High, severity.High

#59 fix: allowed creation of Ingredient with 2 fields
  src/main/java/seedu/address/logic/parser/RecipeBookParserUtil.java
  src/main/java/seedu/address/logic/parser/RecipeBookSyntax.java
  src/main/java/seedu/address/model/recipe/Ingredient.java
  src/main/java/seedu/address/newstorage/JsonAdaptedIngredient.java
Labels: type.Bug, priority.High, severity.High

#61 feat: add DELETE command to McKitchen
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddRecipeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/main/java/seedu/address/model/recipe/Recipe.java
Labels: priority.High

#64 feat!: add ViewCommand Feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Story, priority.High

#63 feat!: add FindCommand feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddRecipeCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/recipe/RecipeContainsKeywordPredicate.java
  src/main/java/seedu/address/model/recipe/SearchSet.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Story, priority.High

#71 chore: minor refactoring of parse and usage messages
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: type.Chore

#72 fix: FindCommand is now case-insensitive
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/recipe/RecipeContainsKeywordPredicate.java
  src/main/java/seedu/address/model/recipe/SearchSet.java
Labels: priority.High, severity.High

#73 test: add tests for storage's functionalities
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/oddcorner.md
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/newstorage/JsonAdaptedIngredient.java
  src/main/java/seedu/address/newstorage/JsonAdaptedRecipe.java
  src/main/java/seedu/address/newstorage/JsonAdaptedStep.java
  src/main/java/seedu/address/newstorage/JsonAdaptedTag.java
  src/main/java/seedu/address/newstorage/JsonSerializableRecipeBook.java
  src/test/data/JsonRecipeBookStorageTest/invalidAndValidRecipeBook.json
  src/test/data/JsonRecipeBookStorageTest/invalidRecipeBook.json
  src/test/data/JsonRecipeBookStorageTest/notJsonFormatRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/duplicateRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/invalidRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipeBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/address/storage/JsonRecipeBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableRecipeBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/OldStorageManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/RecipeBuilder.java
  src/test/java/seedu/address/testutil/TypicalRecipes.java
Labels: priority.High

#79 feat!: implement ListCommand
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: type.Story, priority.High

#81 feat!: implement ExitCommand
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: type.Story, priority.High

#84 feat!: access (view/delete) recipe by index
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/RecipeBookSyntax.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: type.Story, priority.High

#97 test: improve code coverage for the files below
  src/test/java/seedu/address/model/recipe/CompletionTimeTest.java
  src/test/java/seedu/address/model/recipe/NameTest.java
  src/test/java/seedu/address/model/recipe/ServingSizeTest.java
  src/test/java/seedu/address/model/recipe/StepTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.High, type.Test

#99 test: improve code coverage for SearchSet
  src/main/java/seedu/address/model/recipe/SearchSet.java
  src/test/java/seedu/address/model/recipe/SearchSetTest.java
Labels: priority.High, type.Test

#89 Refactor: refactor and standardize Command classes, fix Delete and View commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/RecipeBookParserUtil.java
Labels: severity.High

#107 docs: update project page
  docs/index.md
Labels: priority.High

#111 test: improve CC for RecipeBookSyntax
  src/test/java/seedu/address/logic/parser/RecipeBookSyntaxTest.java
Labels: priority.High, type.Test

#106 test: update CommandTestUtil
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: priority.High, type.Test

#112 refactor: update test method names
  src/test/java/seedu/address/model/recipe/CompletionTimeTest.java
  src/test/java/seedu/address/model/recipe/NameTest.java
  src/test/java/seedu/address/model/recipe/SearchSetTest.java
  src/test/java/seedu/address/model/recipe/ServingSizeTest.java
  src/test/java/seedu/address/model/recipe/StepTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Test

#109 test: improve code coverage for Prefix
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/parser/PrefixTest.java
Labels: priority.High, type.Test

#105 test: increase code coverage for RecipeContainsKeywordPredicate
  src/main/java/seedu/address/model/recipe/RecipeContainsKeywordPredicate.java
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipeBook.json
  src/test/java/seedu/address/model/recipe/RecipeContainsKeywordPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalRecipes.java
Labels: priority.High, type.Test

#116 Feat!: Update UI to support rendering of recipe contents
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecipeCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/CremeTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecipeListCard.fxml
  src/main/resources/view/RecipeListPanel.fxml
  src/main/resources/view/RecipeListPanelAndCard.css
  src/main/resources/view/ResultDisplay.css
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/fonts/Chivo-Italic.ttf
Labels: priority.High

#113 test: include test for FindCommand and its parser
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/recipe/RecipeContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalRecipes.java
Labels: priority.High, type.Test

#127 feat!: Add feature clear
  src/main/java/seedu/address/logic/commands/CancelClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ConfirmedClearCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
Labels: priority.High

#140 docs: update UG and DG for clear and storage
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/test/java/seedu/address/logic/commands/CancelClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ConfirmedClearCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
Labels: type.Chore, priority.High

#138 Test: Update DeleteCommandTest
  docs/DeveloperGuide.md
  docs/umlDiagrams/DeleteSequenceDiagram.puml
  docs/umlDiagrams/img/ArchitectureDiagram.png
  docs/umlDiagrams/img/ArchitectureSequenceDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Test

#131 Test: Update IngredientTest
  src/main/java/seedu/address/model/recipe/Ingredient.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/model/recipe/IngredientTest.java
Labels: priority.High, type.Test

#148 fix: ViewCommand and IngredientTest issues
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/model/recipe/IngredientTest.java
Labels: priority.High, type.Test

#149 Docs: update command summary section with add and edit commands
  docs/UserGuide.md
Labels: priority.High

#135 Test: add tests for ClearCommand
  docs/DeveloperGuide.md
Labels: priority.High, type.Test

#142 feat!: add resetCommand to reset the recipe book back to the preloaded recipes
  src/main/java/seedu/address/logic/commands/CancelResetCommand.java
  src/main/java/seedu/address/logic/commands/ConfirmedResetCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/main/java/seedu/address/logic/parser/ResetCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/testutil/TypicalRecipes.java
Labels: type.Enhancement, priority.High

#153 feat!: implement HelpCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Story, priority.High, type.Test

#157 refactor: update recipeBook ModelManager and recipeUserPref
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RecipeBookUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/test/java/seedu/address/logic/commands/CancelClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CancelResetCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ConfirmedClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ConfirmedResetCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: type.Chore, priority.High

#152 test: update test files for the Model
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RecipeBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/recipe/UniqueRecipeList.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/RecipeBookTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/recipe/RecipeTest.java
  src/test/java/seedu/address/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.High, type.Test

#158 docs: update delete command in UG
  docs/UserGuide.md
Labels: priority.High

#160 fix: DeleteCommandParser issue
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: priority.High

#163 docs: update FAQ in UG
  docs/UserGuide.md
Labels: priority.High

#164 fix: add ability to scroll in result display for viewing long recipes
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecipeListPanel.fxml
  src/main/resources/view/ResultDisplay.css
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug, severity.High

#159 Chore: Populate sample recipes
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/parser/RecipeBookParser.java
  src/main/java/seedu/address/model/util/RecipeList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
Labels: type.Chore, priority.High

#162 docs: update UG
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: type.Chore, priority.High

#156 Tests: add tests for EditCommand and EditCommandParser
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/RecipeBookParserUtil.java
  src/main/java/seedu/address/model/recipe/Name.java
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipeBook.json
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/recipe/NameTest.java
  src/test/java/seedu/address/testutil/TypicalRecipes.java
Labels: priority.High

#173 docs: update command format
  docs/UserGuide.md
Labels: type.Chore

#126 Tests: add tests for AddCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/RecipeBookParserUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.High, type.Test

#172 test: add test for ViewCommandParser
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High, type.Test
